# Aula 2 - Numpy: Arrays

Prof. Tiago Dias

[Linkedin](https://www.linkedin.com/in/diasctiago/) | [Github](https://github.com/diasctiago) | [Blog](https://www.dadosaocubo.com/)

## O que é NumPy?

O NumPy oferece funções matemáticas, geradores de números aleatórios, rotinas de álgebra linear, transformadas de Fourier e muito mais.

Com o NumPy é possível trabalhar com numeros em todas as suas formas, como exemplificado na figura abaixo.

| ![Dados](https://i0.wp.com/dadosaocubo.com/wp-content/uploads/2020/07/image1-3.png?w=880&ssl=1) |
|:--:| 
| **Figura** – _Escalares, vetores, matrizes e tensores_ (Fonte da imagem: internet, autor desconhecido) |

*   **Escalar -** O escalar é um número qualquer
*   **Vetor -** O vetor são vários escalares em uma representação unidimensional (uma dimensão)
*   **Matriz -** A matriz são vetores bidimensionais (duas dimensões)
*   **TENSOR** - O tensor são as junções de matrizes (três dimensões)



## Prática com numpy

In [ ]:
# Instalando a biblioteca
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
# importando a biblioteca
import numpy as np

O elemento básico do NumPy é o **ndarray** e é dessa forma que trabalhamos com os valores no NumPy.

In [ ]:
# criando um array com Numpy
vetor = np.array([1,2,3,4,5])

In [ ]:
# listando o array
vetor

array([1, 2, 3, 4, 5])

In [ ]:
# verificando o tipo do array
type(vetor)

numpy.ndarray

In [ ]:
# criando um array de strings com Numpy
vetor_string = np.array(['a','b','c','d','e'])

In [ ]:
# listando o array
vetor_string

array(['a', 'b', 'c', 'd', 'e'], dtype='<U1')

In [ ]:
# verificando o tipo do array
type(vetor_string)

numpy.ndarray

### Qual a diferença entre uma lista e um array NumPy?

In [ ]:
# criando um array misto com Numpy
vetor_misto = np.array([1,'a',2,'b',3])

In [ ]:
# listando o vetor misto
vetor_misto

array(['1', 'a', '2', 'b', '3'], dtype='<U21')

In [ ]:
# criando uma lista mista
lista_mista = [1,'a',2,'b',3]

In [ ]:
# listando a lista mista
lista_mista

[1, 'a', 2, 'b', 3]

Enquando as listas não precisam ser homogeneas, os vetores arrays NumPy devem ser homogeneos. Isso torna mais rápido e eficiente de criar e manipular dados numéricos dentro dos arrays NumPy.

### Funções com NumPy

In [ ]:
# criando um array de zeros
np.zeros(8, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# criando um array de uns
np.ones(10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
# criando um array de números específicos
np.full(10,7, dtype=float)

array([7., 7., 7., 7., 7., 7., 7., 7., 7., 7.])

In [ ]:
# criando um array com range
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# range com start, stop (exclusivo) e step
np.arange(1,20,2) 

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
# função range do python
range(20)

range(0, 20)

In [ ]:
# criando um array com linspace, stop (não exclusivo)
np.linspace(0,20,num=30)

array([ 0.        ,  0.68965517,  1.37931034,  2.06896552,  2.75862069,
        3.44827586,  4.13793103,  4.82758621,  5.51724138,  6.20689655,
        6.89655172,  7.5862069 ,  8.27586207,  8.96551724,  9.65517241,
       10.34482759, 11.03448276, 11.72413793, 12.4137931 , 13.10344828,
       13.79310345, 14.48275862, 15.17241379, 15.86206897, 16.55172414,
       17.24137931, 17.93103448, 18.62068966, 19.31034483, 20.        ])

In [ ]:
# criando um array
arr = np.array([2,5,20,1,55,33,76,20,10]) 
arr

array([ 2,  5, 20,  1, 55, 33, 76, 20, 10])

In [ ]:
# ordenando o array
np.sort(arr)

array([ 1,  2,  5, 10, 20, 20, 33, 55, 76])

In [ ]:
# ordenando o array decrescente
-np.sort(-arr)

array([76, 55, 33, 20, 20, 10,  5,  2,  1])

In [ ]:
# juntando arrays
array_a = np.array([1,3,5,7])
array_a

array([1, 3, 5, 7])

In [ ]:
array_b = np.array([2,4,6,8])
array_b

array([2, 4, 6, 8])

In [ ]:
# contatenando sem ordenação
np.concatenate((array_a,array_b))

array([1, 3, 5, 7, 2, 4, 6, 8])

In [ ]:
# concatenando de forma ordenada
np.sort(np.concatenate((array_a,array_b)))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# verificando a dimensão de um array
arr.ndim

1

In [ ]:
# verificando o tamanho de um array
arr.size

9

In [ ]:
# verificando o tamanho de elementos e dimensões de um array
arr.shape

(9,)

In [ ]:
arr

array([ 2,  5, 20,  1, 55, 33, 76, 20, 10])

In [ ]:
# acessando array por indice, primeiro e último item
arr[0], arr[-1]

(2, 10)

In [ ]:
# imprimindo lista com indices e valores
for indice, valor in zip(np.arange(arr.size), arr):
  print(f'Indice {indice} - Valor {valor}')

Indice 0 - Valor 2
Indice 1 - Valor 5
Indice 2 - Valor 20
Indice 3 - Valor 1
Indice 4 - Valor 55
Indice 5 - Valor 33
Indice 6 - Valor 76
Indice 7 - Valor 20
Indice 8 - Valor 10


In [ ]:
# lista com zip de indice e valores
list(zip(np.arange(arr.size), arr))

[(0, 2), (1, 5), (2, 20), (3, 1), (4, 55), (5, 33), (6, 76), (7, 20), (8, 10)]

In [ ]:
# fatiando o array
arr[:4]

array([ 2,  5, 20,  1])

In [ ]:
arr[4:]

array([55, 33, 76, 20, 10])

In [ ]:
arr[2:5]

array([20,  1, 55])

In [ ]:
# soma, maximo e minimo de um array
sum(arr), max(arr), min(arr)

(222, 76, 1)

In [ ]:
# copiando um array
arr2 = arr

In [ ]:
arr2

array([ 2,  5, 20,  1, 55, 33, 76, 20, 10])

In [ ]:
arr

array([ 2,  5, 20,  1, 55, 33, 76, 20, 10])

In [ ]:
arr2 = arr.copy()

In [ ]:
arr, arr2

(array([ 2,  5, 20,  1, 55, 33, 76, 20, 10]),
 array([ 2,  5, 20,  1, 55, 33, 76, 20, 10]))

In [ ]:
# somando 2 arrays
soma = arr + arr2
soma

array([  4,  10,  40,   2, 110,  66, 152,  40,  20])

In [ ]:
# NÃO é possível fazer operações com shapes diferentes
arr + np.array([1,2,3,4])

ValueError: ignored

In [ ]:
# Completando o array para somar
arr + np.concatenate((np.array([1,2,3,4]), np.zeros(5)))

array([ 3.,  7., 23.,  5., 55., 33., 76., 20., 10.])

In [ ]:
# subtraindo 2 arrays
sub = arr - arr
sub

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# aplicando negativo em todos os elementos
-arr

array([ -2,  -5, -20,  -1, -55, -33, -76, -20, -10])

In [ ]:
# multiplicando 2 arrays
multi = arr * arr
multi

array([   4,   25,  400,    1, 3025, 1089, 5776,  400,  100])

In [ ]:
# dividindo 2 arrays
div = arr / arr
div

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
div = arr // arr
div

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
div = arr % arr
div

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr / np.array(2)

array([ 1. ,  2.5, 10. ,  0.5, 27.5, 16.5, 38. , 10. ,  5. ])

In [ ]:
# dúvida sobre divisões com listas
lista1 = [1,2,3]
lista2 = [2]
lista3 = [n/lista2[0] for n in lista1]

In [ ]:
lista3

[0.5, 1.0, 1.5]

### Estudo de Caso

Como criar um array a partir de uma lista, expor suas informações (dimensões e elementos), identificar elementos específicos e realizar operações matemáticas?

In [ ]:
lista = [1,3,6,33,55,90,77,45,32,12,4]

In [ ]:
array_lista = np.array(lista)
array_lista

array([ 1,  3,  6, 33, 55, 90, 77, 45, 32, 12,  4])

In [ ]:
np.sort(array_lista)

array([ 1,  3,  4,  6, 12, 32, 33, 45, 55, 77, 90])

In [ ]:
array_lista

array([ 1,  3,  6, 33, 55, 90, 77, 45, 32, 12,  4])

In [ ]:
array_lista.shape, array_lista.size, array_lista.ndim

((11,), 11, 1)

In [ ]:
array_lista[3]

33

In [ ]:
array_lista[4]

55

In [ ]:
array_lista + array_lista

array([  2,   6,  12,  66, 110, 180, 154,  90,  64,  24,   8])

In [ ]:
array_lista + 10

array([ 11,  13,  16,  43,  65, 100,  87,  55,  42,  22,  14])

In [ ]:
array_lista * array_lista

array([   1,    9,   36, 1089, 3025, 8100, 5929, 2025, 1024,  144,   16])

In [ ]:
array_lista * 10

array([ 10,  30,  60, 330, 550, 900, 770, 450, 320, 120,  40])

## Atividade

**Questão 1 -** Crie uma lista do Python que contenha 30 inteiros aleatórios (entre 0 e 100). Em seguida, a partir da lista criada anteriormente, crie um array do Numpy, utilizando a função array.

In [ ]:
# números aleatórios entre 0 e 1


In [ ]:
# números aleatórios inteiros


**Questão 2 -** Crie um array com 10 elementos (iniciando em zero), em que os elementos tenham um intervalo de 3 unidades entre si.

**Questão 3 -** Para o array aleatório gerado na questão 1, obtenha:
* O primeiro item
* O último item
* O valor mínimo
* O valor máximo
* A posição do valor mínimo
* A posição do valor máximo


In [ ]:
# O primeiro item


In [ ]:
# O último item


In [ ]:
# O valor mínimo


In [ ]:
# O valor máximo


In [ ]:
# A posição do valor mínimo


In [ ]:
# A posição do valor máximo


**Questão 4 -** Para o array aleatório gerado na questão 2, obtenha:
* A soma
* A média
* A mediana
* A variância
* O desvio padrão

In [ ]:
# soma


In [ ]:
# media


In [ ]:
# mediana


In [ ]:
# variancia


In [ ]:
# desvio padrao


**Questão 5 -** Solicite um input do usuário de 10 números separados por vírgula, crie um array somente com os números pares e impirma o resultado para o usuário.